### PR TITLE
Adds the loading of the info-content data

### PR DESCRIPTION
**Pull request by PhillipsOwen**
this PR adds the loading of a new cache for the information content data.

### CODE REVIEW

**Review by cbizon — COMMENTED** [review]
I don't see where you are getting the  ic out of redis?

When we do get it out, we may have a case where both conflated entities have their own ic, in which case we should choose the minimum one.

Do you really want to set all the databases to 0 in the config?

**Comment by PhillipsOwen** [comment]
> 
> 
> I don't see where you are getting the ic out of redis?
> 
> When we do get it out, we may have a case where both conflated entities have their own ic, in which case we should choose the minimum one.
> 
> Do you really want to set all the databases to 0 in the config?

this part just gets the data into redis. i have not worked on getting it out of redis for the website.

all the redis caches use db 0. presumably there is only 1 db per redis instance.

**Comment by YaphetKG** [comment]
Connections, and redis setup look good. For local testing maybe having different db (0-6) on the default config might be a good idea (since the default config refers to a single redis instance )

**Review by YaphetKG — APPROVED** [review]
actually tests redis yaml is changed to refer to db- 0 . That should be fine

**Pull request merged**
