### PR TITLE
Update openAPI config for smart api registration

### PR DESCRIPTION
**Pull request by kshefchek**
Updates openAPI config - see https://fastapi.tiangolo.com/advanced/extending-openapi/

### CODE REVIEW

**Comment by PhillipsOwen** [comment]
this looked good to me. i like how you pulled the API mods to another file.

did you use my write-up to do this? if so, is there anything in there that should be updated?

**Review by PhillipsOwen — COMMENTED** [review]
this looked good to me. i like how you pulled the API mods to another file.

did you use my write-up to do this? if so, is there anything in there that should be updated?

**Comment by kshefchek** [comment]
@PhillipsOwen yes the write up was super helpful, the only thing that was missing that I added was the import statement ```from fastapi.openapi.utils import get_openapi```

Do I need to do anything from here like installing the spec on open-api.info or is that something you will handle?

**Comment by PhillipsOwen** [comment]
ah i see that someone named "all anonymous users" (haha) already modified the doc a bit. if that was you, thanks!

**Comment by kshefchek** [comment]
ah yes sorry meant to say I already added it!  I'll look for the production update then do the rest of the steps

**Pull request merged**
