### PR TITLE
Fix overlooked trapi updates

### PR DESCRIPTION
**Pull request by jdr0887**

### CODE REVIEW

**Review by cbizon — APPROVED** [review]
Did the server version get bumped in the last PR?

**Comment by jdr0887** [comment]
It did not.  It is fixed in this PR, though.

**Comment by cbizon** [comment]
That's the trapi version, but not I think the app version, which is set in https://github.com/TranslatorSRI/NodeNormalization/blob/master/node_normalizer/resources/openapi.yml
Looks like 2.0.28 which is the same as the live version, so it should get bumped to 2.0.29

**Comment by jdr0887** [comment]
You are right.  I created a docker image locally, but with the version bumped to 2.0.9, but didn't see the app version in there.  I will fix that now.

**Pull request merged**
