### PR TITLE
initial implementation chem conflation

### PR DESCRIPTION
**Pull request by cbizon**
Adds in a drug/chemical conflation

### CODE REVIEW

**Comment by cbizon** [comment]
I have a Babel branch that creates the necessary conflation file.   Im just testing it a bit more before PR

**Comment by cbizon** [comment]
I'm going to make a couple changes - converting to draft.  I think that we want to set the parameters so that default behavior is not changed at this point, and then we will update them to be more coherent after Sept.

**Comment by cbizon** [comment]
So what I did was to add a new parameter called drug_chemical_conflation, with a default of False.  This way, nobody needs to change their calls right now, and they will get the same expected behavior.  Once this makes it up to prod & is in use, we will revisit, changing the name of the original conflation parameter to gene_protein_conflation and possibly setting the default for the new conflation to true.

**Review by gaurav — APPROVED** [review]
Seems to be working well!

**Pull request merged**
